version: '3.8'

services:
  config-server:
    build:
      context: ./analizator-config-server
    container_name: config-server
    ports:
      - 8888:8888
    networks:
      - microservices-network
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/LaaLkA/analizator-config.git"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  eureka-server: 
    build:
      context: ./analizator-eureka-server
    container_name: eureka-server
    depends_on:
      - config-server
    ports:
      - 8761:8761
    networks:
      - microservices-network
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
#      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      SPRING_APPLICATION_NAME: eureka-server
    restart: always

  api-gateway:
    build:
      context: ./analizator-api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - 8080:8080
    networks:
      - microservices-network
    restart: always

  user-service:
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - 8081:8081
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    networks:
      - microservices-network
    environment:
      SPRING_DATASOURCE_USERNAME: "Auser"
      SPRING_DATASOURCE_PASSWORD: "123"
    restart: always

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: Auser
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    networks:
      - microservices-network
    restart: always


networks:
  microservices-network:
    driver: bridge